version: "3.7"

services:
  app:
    build: .
    container_name: movie_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
